name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: cd Front-end-mobile && npm install
      run: cd Front-end-mobile && npm i
    - name: install react-native-cli
      run: cd Front-end-mobile && npm install -g react-native-cli
    - name: react-native assets bundle update android
      run: cd Front-end-mobile && react-native bundle --platform android --dev false --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/res/
    - name: delete duplicate ressources
      run: cd Front-end-mobile && rm -rf ./android/app/src/main/res/drawable-* && rm -rf ./android/app/src/main/res/raw
    - name: gradle clean cache
      run: cd Front-end-mobile/android && gradle clean
    - name: Grant execute permission for gradlew
      run: cd Front-end-mobile/android && chmod +x gradlew
    - name: Build with Gradle
      run: cd Front-end-mobile/android && ./gradlew build
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: npm install
        run: cd Front-end-mobile && npm i
      - name: install react-native-cli
        run: cd Front-end-mobile && npm install -g react-native-cli
      - name: react-native assets bundle update android
        run: cd Front-end-mobile && react-native bundle --platform android --dev false --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/res/
      - name: gradle clean cache
        run: cd Front-end-mobile/android && gradle clean
      - name: Build debug APK
        run: cd Front-end-mobile/android && bash ./gradlew assembleRelease --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: cd Front-end-mobile/android && app/build/outputs/apk/debug/app-debug.apk