name: Deploy back-end

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: set working directory to back-end
        run: cd Back-end
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "rela-ressources-api"
          heroku_email: "langlois.william.pro@gmail.com"
          usedocker: true
