name: deploy_web
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          appdir: ./Front-end-web
          heroku_api_key: ${{secrets.HEROKU_API_KEY_WEB}}
          heroku_app_name: "gentle-basin-24713"
          heroku_email: "theo27400@live.fr"